### ISSUE TITLE
H5移动兼容性没有覆盖到iOS8

### ISSUE THREAD

**Issue by pingan1927** [ant-tool/atool-build#212]
`display: flex`
实际项目中构建出来的兼容性样式少了`display: -webkit-flex;`

通过dora起服务则会渲染出这个兼容样式。

验证很简单
创建一个less文件
`
.flex-test {
    display: flex;
}
`
运行下`atool-build`即可看到结果。

**Comment by pigcan** [comment]
https://github.com/ant-tool/atool-build/issues/190

**Comment by pigcan** [comment]
发现压缩时会进行优化

```css
.flex-test {
  display: -webkit-box;
  display: -webkit-flex;
  display: flex;
}
```
 会被自动省略成

```css
.flex-test {
  display: -webkit-box;
  display: flex;
}
```

webpack 中对应的样式压缩是在 css-loader 中实现的，对于压缩的规则需要手动配置 css-nano 参数进行传递。

`css-loader?-autoprefix`
